### ISSUE TITLE
Will not load

### ISSUE THREAD

**Issue by donnyp02** [sunkid/CreativeStick#1]
I have a new installation of the newest build bukkit, creativestick, and basebukkitplugin, those are the only two plugins in the plugins folder, and here is the error I'm getting.

16:28:42 [INFO] [CreativeStick 0.8] initialized
16:28:42 [INFO] [BaseBukkitPlugin 1.7] initialized
16:28:42 [INFO] Preparing level "Donny's Back Porch"
16:28:42 [INFO] Default game type: 0
16:28:42 [INFO] Preparing start region for level 0 (Seed: -5653745541195056466)
16:28:43 [INFO] Preparing start region for level 1 (Seed: 6055616041864363950)
16:28:43 [INFO] [CreativeStick 0.8] Server version compatibility check succeeded

16:28:43 [SEVERE] Error occurred while enabling CreativeStick v0.8 (Is it up to
date?): com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configu
ration/file/FileConfiguration;
java.lang.NoSuchMethodError: com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig
()Lorg/bukkit/configuration/file/FileConfiguration;
        at com.iminurnetz.bukkit.plugin.util.ConfigurationService.load(Configura
tionService.java:76)
        at com.iminurnetz.bukkit.plugin.util.ConfigurationService.<init>(Configu
rationService.java:53)
        at com.iminurnetz.bukkit.plugin.creativestick.CSConfigurationService.<in
it>(CSConfigurationService.java:73)
        at com.iminurnetz.bukkit.plugin.creativestick.CSPlugin.setup(CSPlugin.ja
va:586)
        at com.iminurnetz.bukkit.plugin.creativestick.CSPlugin.enablePlugin(CSPl
ugin.java:562)
        at com.iminurnetz.bukkit.plugin.BukkitPlugin.onEnable(BukkitPlugin.java:
148)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:941)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:280)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:174)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:157
)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
16:28:43 [INFO] [BaseBukkitPlugin 1.7] Server version compatibility check succee
ded
16:28:43 [INFO] Server permissions file permissions.yml is empty, ignoring it
16:28:43 [INFO] Done (0.109s)! For help, type "help" or "?"

Any suggestions?
Thanks!

**Comment by donnyp02** [comment]
Had to update.... thought I already had, works great thanks!!
