### ISSUE TITLE
Creative stick no longer loading with R4

### ISSUE THREAD

**Issue by andrewkm** [sunkid/CreativeStick#3]
Using your newest versions for R4 2.91 and 1.11

Getting this on startup

2012-02-05 06:04:28 [SEVERE] Could not load 'plugins\Armageddon.jar' in folder 'plugins': 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:285)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:200)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:190)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:166)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:52)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.NullPointerException
    at org.bukkit.plugin.PluginLogger.<init>(PluginLogger.java:24)
    at org.bukkit.plugin.java.JavaPlugin.getLogger(JavaPlugin.java:374)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.log(BukkitPlugin.java:78)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.<init>(BukkitPlugin.java:73)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.<init>(ArmageddonPlugin.java:86)
    ... 13 more
2012-02-05 06:04:28 [INFO] Starting Minequery server on *:25566
2012-02-05 06:04:28 [INFO] [PermissionsEx] sql backend registered!
2012-02-05 06:04:28 [INFO] [PermissionsEx] file backend registered!
2012-02-05 06:04:28 [INFO] [PermissionsEx] PermissionEx plugin initialized.
2012-02-05 06:04:28 [INFO] [PermissionsEx] p2compat backend registered!
2012-02-05 06:04:28 [INFO] [PermissionsCompat] Compatibility Layer Initalized!
2012-02-05 06:04:29 [SEVERE] Could not load 'plugins\CreativeStick.jar' in folder 'plugins': 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:285)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:200)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:190)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:166)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:52)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.NullPointerException
    at org.bukkit.plugin.PluginLogger.<init>(PluginLogger.java:24)
    at org.bukkit.plugin.java.JavaPlugin.getLogger(JavaPlugin.java:374)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.log(BukkitPlugin.java:78)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.<init>(BukkitPlugin.java:73)
    at com.iminurnetz.bukkit.plugin.creativestick.CSPlugin.<init>(CSPlugin.java:55)
    ... 13 more

**Comment by sunkid** [comment]
This was a problem with Armageddon, not CreativeStick. It is fixed in [version 2.92 of Armageddon](https://github.com/sunkid/Armageddon/raw/master/release/Armageddon.jar).
